plex:
  api_endpoint:
  token:


tvdb:
  host: "https://api.thetvdb.com"
  user:
  userkey:
  api_key:


logging:
  date_format: "ISO"
  use_utc: True
  min_level: "INFO"
  disable_processors: False
  use_colors: False


whitelisted_libraries: ""